declare const styles: {
    readonly section: string;
    readonly header: string;
    readonly timeline: string;
    readonly card: string;
    readonly active: string;
    readonly cardBorder: string;
    readonly cardContent: string;
    readonly hoverContent: string;
    readonly phase: string;
    readonly badge: string;
    readonly foundation: string;
    readonly execution: string;
    readonly leadership: string;
    readonly outcome: string;
    readonly outcomeLine: string;
    readonly outcomeHighlight: string;
    readonly outcomeSub: string;
};
export default styles;
