declare const styles: {
    readonly section: string;
    readonly sectionAlt: string;
    readonly header: string;
    readonly grad: string;
    readonly outcomesTwoCol: string;
    readonly colTitle: string;
    readonly outcomeList: string;
    readonly outcomeItem: string;
    readonly oiIcon: string;
    readonly outcomesRight: string;
    readonly growthMap: string;
    readonly growthItem: string;
    readonly growthIcon: string;
    readonly heads: string;
    readonly leaders: string;
    readonly founders: string;
    readonly execs: string;
    readonly finalNote: string;
};
export default styles;
