declare const styles: {
    readonly scrollSection: string;
    readonly scrollTrack: string;
    readonly scrollPanel: string;
    readonly hero: string;
    readonly heroContent: string;
    readonly heroTitle: string;
    readonly heroLine: string;
    readonly heroWhy: string;
    readonly heroLaunchpad: string;
    readonly heroDiff: string;
    readonly lpWord: string;
    readonly old: string;
    readonly oldContent: string;
    readonly choose: string;
    readonly oldWarning: string;
    readonly oldList: string;
    readonly features: string;
    readonly feature: string;
    readonly icon: string;
    readonly oldTitle: string;
    readonly oldText: string;
    readonly system: string;
    readonly systemContent: string;
    readonly stats: string;
    readonly newSystemTitle: string;
    readonly newSystemDesc: string;
    readonly cardGrid: string;
    readonly card: string;
    readonly outcome: string;
    readonly outcomeContent: string;
    readonly cta: string;
    readonly ctaButton: string;
    readonly [key: string]: string;
};
export default styles;
